apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  name: default
  namespace: istio-system
spec:
  memberSelectors: 
  - matchLabels: 
      istio-injection: enabled 